version: '3'
services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: python -m flask run --host=0.0.0.0 --port=5000 --reload

    #command: flask run --host=0.0.0.0 --port=5000 --reload